server:
  port: 8081

# 数据库的相关配置
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource  # 底层使用druid连接池
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sb?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    username: glue
    password: Glue01_glue

    # 连接池的配置信息
    druid:
      initial-size: 5 #初始化连接数
      max-active : 30 #最大连接数
      min-idle: 5 #最小连接
      max-wait: 60000
      validation-query: SELECT 1 FROM DUAL
      min-evictable-idle-time-millis: 300000
      test-while-idle: true
      filters: stat,wall,slf4j
      stat-view-servlet:
        login-username: admin
        login-password: admin
        url-pattern: /druid/*
        allow: 127.0.0.1    # IP白名单
        reset-enable: false
        enabled: true
  # banner的配置
  main:
    banner-mode: off #关闭banner
  # 热部署的配置
  devtools:
    restart:
      enabled: true   # 开启热部署
      additional-paths: /src/main/java  #该路径下的东西如果修改就会触发热部署
      exclude: WEB-INF/**     # 不需要热部署管理
      # 最后要在idea中设置自动编译，才会触发热部署

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.chason.pojo # 给当前报的所有类起别名

# 整合logback
# logging:
  # level:
    # com.chason.mapper: trace # 打印mybatis的sql语句

