spring:
  application:
    name: demo03
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sb?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    username: glue
    password: Glue01_glue

server:
  port: 8081

mybatis:
  mapper-locations: classpath:mapper/*.xml
